### ISSUE TITLE
僕は中国語でコンパイルできますか。

### ISSUE THREAD

**Issue by Mayomi** [erozabesu/YPLKart#25]
言葉のファイルがありませんが。

ご建議もあります、Ｍｙｓｑｌデ—タベ—スが増やせますか。

日本語が苦手ですから、すみません。

**Comment by erozabesu** [comment]
Thx for Comment.
Ok. I'll create laungage System with yml file.

But mysql is difficult for me. probably, I would charrenge mysql in future.

**Comment by Mayomi** [comment]
Can I change your code? just fork your project.

**Comment by erozabesu** [comment]
OK, please try it.

**Comment by Mayomi** [comment]
ありがとうございます
